apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dotnetlinux
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnetlinux
    spec:
      containers:
        - image: "wearetherock/dotnet-web"
          imagePullPolicy: Always
          name: dotnetlinux
          ports:
            - containerPort: 80